// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS66wntV1xghDg-0ZpFUYlyifoR2uovaM',
    appId: '1:992201840808:web:4268e2b137d3a824bb0a9d',
    messagingSenderId: '992201840808',
    projectId: 'music-app-eddbb',
    authDomain: 'music-app-eddbb.firebaseapp.com',
    storageBucket: 'music-app-eddbb.firebasestorage.app',
    measurementId: 'G-JH1Q5ZLL76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBte97bCQ1fIPMGtIDw4jQoRFM_XZqcOE',
    appId: '1:992201840808:android:6e0c87f5842de14abb0a9d',
    messagingSenderId: '992201840808',
    projectId: 'music-app-eddbb',
    storageBucket: 'music-app-eddbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJh66H0hQkAeyahe8FwP2-edDTs-NjcnM',
    appId: '1:992201840808:ios:4b39d20583e10207bb0a9d',
    messagingSenderId: '992201840808',
    projectId: 'music-app-eddbb',
    storageBucket: 'music-app-eddbb.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJh66H0hQkAeyahe8FwP2-edDTs-NjcnM',
    appId: '1:992201840808:ios:4b39d20583e10207bb0a9d',
    messagingSenderId: '992201840808',
    projectId: 'music-app-eddbb',
    storageBucket: 'music-app-eddbb.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS66wntV1xghDg-0ZpFUYlyifoR2uovaM',
    appId: '1:992201840808:web:be1af938dc8a0d45bb0a9d',
    messagingSenderId: '992201840808',
    projectId: 'music-app-eddbb',
    authDomain: 'music-app-eddbb.firebaseapp.com',
    storageBucket: 'music-app-eddbb.firebasestorage.app',
    measurementId: 'G-STF1ZRPTHV',
  );
}
